// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ledger struct {
	Id                   []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentBlockHeader   *BlockHeader   `protobuf:"bytes,2,opt,name=current_block_header,json=currentBlockHeader,proto3" json:"current_block_header,omitempty"`
	CurrentBlock         *Block         `protobuf:"bytes,3,opt,name=current_block,json=currentBlock,proto3" json:"current_block,omitempty"`
	GenesisBlock         *Block         `protobuf:"bytes,4,opt,name=genesis_block,json=genesisBlock,proto3" json:"genesis_block,omitempty"`
	BlockHeaders         []*BlockHeader `protobuf:"bytes,5,rep,name=block_headers,json=blockHeaders,proto3" json:"block_headers,omitempty"`
	Blocks               []*Block       `protobuf:"bytes,6,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Events               []*Event       `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Ledger) Reset()         { *m = Ledger{} }
func (m *Ledger) String() string { return proto.CompactTextString(m) }
func (*Ledger) ProtoMessage()    {}
func (*Ledger) Descriptor() ([]byte, []int) {
	return fileDescriptor_63585974d4c6a2c4, []int{0}
}

func (m *Ledger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ledger.Unmarshal(m, b)
}
func (m *Ledger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ledger.Marshal(b, m, deterministic)
}
func (m *Ledger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ledger.Merge(m, src)
}
func (m *Ledger) XXX_Size() int {
	return xxx_messageInfo_Ledger.Size(m)
}
func (m *Ledger) XXX_DiscardUnknown() {
	xxx_messageInfo_Ledger.DiscardUnknown(m)
}

var xxx_messageInfo_Ledger proto.InternalMessageInfo

func (m *Ledger) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Ledger) GetCurrentBlockHeader() *BlockHeader {
	if m != nil {
		return m.CurrentBlockHeader
	}
	return nil
}

func (m *Ledger) GetCurrentBlock() *Block {
	if m != nil {
		return m.CurrentBlock
	}
	return nil
}

func (m *Ledger) GetGenesisBlock() *Block {
	if m != nil {
		return m.GenesisBlock
	}
	return nil
}

func (m *Ledger) GetBlockHeaders() []*BlockHeader {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

func (m *Ledger) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Ledger) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Ledger)(nil), "pb.Ledger")
}

func init() { proto.RegisterFile("ledger.proto", fileDescriptor_63585974d4c6a2c4) }

var fileDescriptor_63585974d4c6a2c4 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4a, 0xc6, 0x30,
	0x14, 0x84, 0x69, 0x7e, 0x8d, 0x98, 0xa6, 0x0a, 0xc1, 0x45, 0xe8, 0xaa, 0xba, 0xea, 0x2a, 0x0b,
	0xf5, 0x02, 0x0a, 0x82, 0x0b, 0x57, 0xb9, 0x40, 0x31, 0xcd, 0xa3, 0x16, 0x4b, 0x5b, 0x92, 0xea,
	0xd5, 0xbc, 0x9e, 0xe4, 0x25, 0xda, 0x88, 0xff, 0x72, 0x66, 0xbe, 0x19, 0x1e, 0x8f, 0xf1, 0x09,
	0xec, 0x00, 0x4e, 0xad, 0x6e, 0xd9, 0x16, 0x41, 0x56, 0x53, 0x97, 0x66, 0x5a, 0xfa, 0xf7, 0x68,
	0xd4, 0xfc, 0x0d, 0x5e, 0xed, 0x4f, 0x5c, 0x97, 0xf0, 0x09, 0xf3, 0x16, 0xc5, 0xcd, 0x17, 0x61,
	0xf4, 0x05, 0xcb, 0xe2, 0x82, 0x91, 0xd1, 0xca, 0xa2, 0x29, 0x5a, 0xae, 0xc9, 0x68, 0xc5, 0x03,
	0xbb, 0xea, 0x3f, 0x9c, 0x83, 0x79, 0xeb, 0x70, 0xac, 0x8b, 0x2b, 0x92, 0x34, 0x45, 0x5b, 0xde,
	0x5e, 0xaa, 0xd5, 0xa8, 0xc7, 0xe0, 0x3f, 0xa3, 0xad, 0x45, 0x82, 0x33, 0x4f, 0x28, 0x56, 0xfd,
	0x99, 0x90, 0x07, 0xec, 0x9e, 0xff, 0x76, 0x35, 0xcf, 0x5b, 0x81, 0x1f, 0x60, 0x06, 0x3f, 0xfa,
	0xc4, 0x9f, 0xfc, 0xe3, 0x53, 0x1e, 0xf9, 0x7b, 0x56, 0xe5, 0xa7, 0x79, 0x79, 0xda, 0x1c, 0x8e,
	0xdd, 0xc6, 0xcd, 0x2e, 0xbc, 0xb8, 0x66, 0x14, 0xb5, 0x97, 0x14, 0xf1, 0x6c, 0x3e, 0x05, 0x01,
	0xc1, 0x2f, 0x79, 0x79, 0xb6, 0x23, 0x4f, 0xc1, 0xd1, 0x29, 0x30, 0x14, 0x1f, 0x78, 0xf7, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x8c, 0x00, 0x47, 0x0d, 0x7c, 0x01, 0x00, 0x00,
}
